


public class CP extends javax.swing.JFrame {

    ControlProducto  productos;
    public  CP() {
        productos = new ControlProducto();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        escritorio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu23 = new javax.swing.JMenu();
        alta_congelado = new javax.swing.JMenu();
        alta_fresco = new javax.swing.JMenu();
        alta_refrigerado = new javax.swing.JMenu();
        bajas = new javax.swing.JMenu();
        reportes = new javax.swing.JMenu();
        buscar = new javax.swing.JMenu();
        cambios = new javax.swing.JMenu();
        calcularPrecio = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        jMenu23.setText("Altas");

        alta_congelado.setText("Producto Congelado");
        alta_congelado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alta_congeladoMouseClicked(evt);
            }
        });
        jMenu23.add(alta_congelado);

        alta_fresco.setText("Producto Fresco");
        alta_fresco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alta_frescoMouseClicked(evt);
            }
        });
        jMenu23.add(alta_fresco);

        alta_refrigerado.setText("Producto Refrigerado");
        alta_refrigerado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alta_refrigeradoMouseClicked(evt);
            }
        });
        jMenu23.add(alta_refrigerado);

        jMenuBar1.add(jMenu23);

        bajas.setText("Bajas");
        bajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bajasMouseClicked(evt);
            }
        });
        jMenuBar1.add(bajas);

        reportes.setText("Reportes");
        reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportesMouseClicked(evt);
            }
        });
        jMenuBar1.add(reportes);

        buscar.setText("Buscar");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        jMenuBar1.add(buscar);

        cambios.setText("Cambios");
        cambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiosMouseClicked(evt);
            }
        });
        jMenuBar1.add(cambios);

        calcularPrecio.setText("Calcular precio");
        calcularPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularPrecioMouseClicked(evt);
            }
        });
        jMenuBar1.add(calcularPrecio);

        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        productos.save();
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void alta_congeladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alta_congeladoMouseClicked
        PC altas = new PC(productos);
        escritorio.add(altas);
        altas.setVisible(true);
    }//GEN-LAST:event_alta_congeladoMouseClicked

    private void reportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesMouseClicked
        VReportesBafar reporte = new VReportesBafar(productos);
        escritorio.add(reporte);
        reporte.setVisible(true);
    }//GEN-LAST:event_reportesMouseClicked

    private void alta_frescoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alta_frescoMouseClicked
        PF reporte = new PF(productos);
        escritorio.add(reporte);
        reporte.setVisible(true);
    }//GEN-LAST:event_alta_frescoMouseClicked

    private void alta_refrigeradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alta_refrigeradoMouseClicked
       PR reporte = new PR(productos);
       escritorio.add(reporte);
       reporte.setVisible(true);
    }//GEN-LAST:event_alta_refrigeradoMouseClicked

    private void bajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bajasMouseClicked
        Bajas bajas = new Bajas(productos);
        escritorio.add(bajas);
        bajas.setVisible(true);
    }//GEN-LAST:event_bajasMouseClicked

    private void calcularPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularPrecioMouseClicked
        CalcularPrecio calcular = new CalcularPrecio(productos);
        escritorio.add(calcular);
        calcular.setVisible(true);
    }//GEN-LAST:event_calcularPrecioMouseClicked

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        Buscar buscar = new Buscar(productos);
        escritorio.add(buscar);
        buscar.setVisible(true);
    }//GEN-LAST:event_buscarMouseClicked

    private void cambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiosMouseClicked
        CambiosPrincipal cambios = new CambiosPrincipal(productos);
        escritorio.add(cambios);
        cambios.setVisible(true);
    }//GEN-LAST:event_cambiosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu alta_congelado;
    private javax.swing.JMenu alta_fresco;
    private javax.swing.JMenu alta_refrigerado;
    private javax.swing.JMenu bajas;
    private javax.swing.JMenu buscar;
    private javax.swing.JMenu calcularPrecio;
    private javax.swing.JMenu cambios;
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenu reportes;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
